## This file is not scoped for this project . Initially tried whith this to run docker lcoally via
##two images together in one container
version: '3.1'
services:
  backend:
    container_name: testdb
    image: kokila1412/spring-docker-demo-db
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - "React"

  React:
    container_name: app
    image: react-app
    ports:
      - "3000:3000"

